/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/head_final.glb -o components/RobotHead.tsx -r public

Ajustes manuais sobre a saída do gltfjsx (v6 ainda emite tipos de React 18):
- JSX.IntrinsicElements['group'] -> ThreeElements['group'] (namespace JSX global
  não existe mais nos tipos do React 19)
- removido `animations: GLTFAction[]` (o modelo não tem animações e o tipo
  GLTFAction nunca era declarado)
*/

import { useEffect } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useThree, type ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: { model: THREE.Mesh }
  materials: { model: THREE.MeshStandardMaterial }
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/head_final.glb') as unknown as GLTFResult
  const gl = useThree((s) => s.gl)

  // Sem anisotropia as texturas PBR borram nas faces em ângulo raso (a lateral
  // do crânio e o pescoço), que é onde o detalhe das placas mais aparece.
  useEffect(() => {
    const max = gl.capabilities.getMaxAnisotropy()
    for (const map of [materials.model.map, materials.model.normalMap, materials.model.roughnessMap, materials.model.metalnessMap]) {
      if (map && map.anisotropy !== max) {
        map.anisotropy = max
        map.needsUpdate = true
      }
    }
  }, [gl, materials])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

useGLTF.preload('/models/head_final.glb')
